#!/bin/bash

# Communities.win Leaderboard - Systemd Service Installation Script
# This script helps you install the leaderboard as a systemd service

set -e

echo "=========================================="
echo "Leaderboard Systemd Service Installer"
echo "=========================================="
echo ""

# Get current directory
CURRENT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CURRENT_USER="$(whoami)"

echo "Detected configuration:"
echo "  User: $CURRENT_USER"
echo "  Directory: $CURRENT_DIR"
echo ""

# Confirm with user
read -p "Is this correct? (y/n) " -n 1 -r
echo ""
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Installation cancelled."
    exit 1
fi

# Check if Node.js is installed
if ! command -v node &> /dev/null; then
    echo "ERROR: Node.js is not installed. Please install Node.js first."
    exit 1
fi

NODE_PATH=$(which node)
echo "Node.js found at: $NODE_PATH"
echo ""

# Create temporary service file
SERVICE_FILE="/tmp/leaderboard-updater.service"
cat > "$SERVICE_FILE" << EOF
# Communities.win Leaderboard Service
# Auto-generated by install-service.sh

[Unit]
Description=Communities.win Leaderboard Server with Auto-Updates
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=$CURRENT_USER
WorkingDirectory=$CURRENT_DIR
ExecStart=$NODE_PATH $CURRENT_DIR/app.js server

# Restart policy
Restart=always
RestartSec=10

# Logging
StandardOutput=append:/var/log/leaderboard.log
StandardError=append:/var/log/leaderboard.log

# Environment
Environment="NODE_ENV=production"
Environment="PORT=3000"

# Security hardening
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=strict
ProtectHome=read-only
ReadWritePaths=$CURRENT_DIR

[Install]
WantedBy=multi-user.target
EOF

echo "Service file created at: $SERVICE_FILE"
echo ""

# Create log file
echo "Setting up log file..."
sudo touch /var/log/leaderboard.log
sudo chown $CURRENT_USER:$CURRENT_USER /var/log/leaderboard.log
echo "Log file created: /var/log/leaderboard.log"
echo ""

# Copy service file
echo "Installing service file..."
sudo cp "$SERVICE_FILE" /etc/systemd/system/leaderboard-updater.service
sudo chmod 644 /etc/systemd/system/leaderboard-updater.service
echo ""

# Reload systemd
echo "Reloading systemd..."
sudo systemctl daemon-reload
echo ""

# Enable service
echo "Enabling service to start on boot..."
sudo systemctl enable leaderboard-updater
echo ""

# Ask if user wants to start now
read -p "Start the service now? (y/n) " -n 1 -r
echo ""
if [[ $REPLY =~ ^[Yy]$ ]]; then
    sudo systemctl start leaderboard-updater
    echo ""
    echo "Service started!"
    sleep 2
    sudo systemctl status leaderboard-updater
else
    echo ""
    echo "Service installed but not started."
    echo "To start it later, run: sudo systemctl start leaderboard-updater"
fi

echo ""
echo "=========================================="
echo "Installation Complete!"
echo "=========================================="
echo ""
echo "Useful commands:"
echo "  sudo systemctl status leaderboard-updater    # Check status"
echo "  sudo systemctl stop leaderboard-updater      # Stop service"
echo "  sudo systemctl restart leaderboard-updater   # Restart service"
echo "  sudo journalctl -u leaderboard-updater -f    # View live logs"
echo "  sudo tail -f /var/log/leaderboard.log        # View log file"
echo ""
echo "Web interface will be available at: http://localhost:3000"
echo ""
